# Settings for compiling trinket camera architecture

# Localized KCONFIG settings
CONFIG_MSM_CAMERA=y
CONFIG_MSM_CAMERA_DEBUG=y
CONFIG_MSMB_CAMERA=y
CONFIG_MSMB_CAMERA_DEBUG=y
CONFIG_MSM_CAMERA_SENSOR=y
CONFIG_MSM_CPP=y
CONFIG_MSM_CCI=y
CONFIG_MSM_CSI20_HEADER=y
CONFIG_MSM_CSI22_HEADER=y
CONFIG_MSM_CSI30_HEADER=y
CONFIG_MSM_CSI31_HEADER=y
CONFIG_MSM_CSIPHY=y
CONFIG_MSM_CSID=y
CONFIG_MSM_EEPROM=y
CONFIG_MSM_ISPIF=y
CONFIG_IMX134=y
CONFIG_IMX132=y
CONFIG_OV9724=y
CONFIG_OV5648=y
CONFIG_GC0339=y
CONFIG_OV8825=y
CONFIG_OV8865=y
CONFIG_s5k4e1=y
CONFIG_OV12830=y
CONFIG_MSM_V4L2_VIDEO_OVERLAY_DEVICE=y
CONFIG_MSMB_JPEG=y
CONFIG_MSM_FD=y


# Flags to pass into C preprocessor
ccflags-y += -DCONFIG_MSM_CAMERA=1
ccflags-y += -DCONFIG_MSM_CAMERA_DEBUG=1
ccflags-y += -DCONFIG_MSMB_CAMERA=1
ccflags-y += -DCONFIG_MSMB_CAMERA_DEBUG=1
ccflags-y += -DCONFIG_MSM_CAMERA_SENSOR=1
ccflags-y += -DCONFIG_MSM_CPP=1
ccflags-y += -DCONFIG_MSM_CCI=1
ccflags-y += -DCONFIG_MSM_CSI20_HEADER=1
ccflags-y += -DCONFIG_MSM_CSI22_HEADER=1
ccflags-y += -DCONFIG_MSM_CSI30_HEADER=1
ccflags-y += -DCONFIG_MSM_CSI31_HEADER=1
ccflags-y += -DCONFIG_MSM_CSIPHY=1
ccflags-y += -DCONFIG_MSM_CSID=1
ccflags-y += -DCONFIG_MSM_EEPROM=1
ccflags-y += -DCONFIG_MSM_ISPIF=1
ccflags-y += -DCONFIG_IMX134=1
ccflags-y += -DCONFIG_IMX132=1
ccflags-y += -DCONFIG_OV9724=1
ccflags-y += -DCONFIG_OV5648=1
ccflags-y += -DCONFIG_GC0339=1
ccflags-y += -DCONFIG_OV8825=1
ccflags-y += -DCONFIG_OV8865=1
ccflags-y += -DCONFIG_s5k4e1=1
ccflags-y += -DCONFIG_OV12830=1
ccflags-y += -DCONFIG_MSM_V4L2_VIDEO_OVERLAY_DEVICE=1
ccflags-y += -DCONFIG_MSMB_JPEG=1
ccflags-y += -DCONFIG_MSM_FD=1

